aktivitas/urls.py
from django.urls import path
from . import views

app_name = 'aktivitas'

urlpatterns = [
    path('', views.Aktivitas),
    path('add/', views.addObject, name='addObject'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('likes/', views.likes, name='likes'),
    path('1st-html/', views.firstHTML, name='firstHTML'),
    path('matkul/', views.matkul, name='matkul'),
    path('matkul/<int:id>',views.matkulDetail),
    path('matkul/delete-course/<int:id>', views.deleteMatkul, name='deleteMatkul'),
]

my_jquery/urls.py
from django.urls import path
from . import views

app_name = 'accordion'

urlpatterns = [
    path('', views.Accordion, name='accordion'),
]

my_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('activity/', include('aktivitas.urls')),
    path('accordion/', include('my_jquery.urls')),
    path('search/', include('story8.urls')),
    path('djangologin/', include('story9.urls')),
]

story8/urls.py
from django.urls import path
from . import views

app_name = 'story8'

urlpatterns = [
    path('', views.Search, name='search'),
    path('data/', views.SearchInput, name='searchInput'),
]

story9/urls.py
from django.urls import path, include
from . import views

app_name = 'story9'

urlpatterns = [
    path('', views.Story9, name='index'),
    path('register/', views.Register, name='register'),
    path('', include('django.contrib.auth.urls'), name='django-auth'),
]

aktivitas/models.py
from django.db import models

class Activity(models.Model):
    name = models.CharField(max_length = 25)
    description = models.TextField(max_length=500, blank=True)
    
class Person(models.Model):
    name = models.CharField(max_length = 25)
    activity = models.ForeignKey(Activity, on_delete=models.CASCADE) #Many to one

home/models.py
from django.db import models

class Matkul(models.Model):
    name = models.CharField(max_length = 25)
    credit = models.TextField(default=1)
    lecturer = models.TextField(max_length = 25)
    description = models.TextField(blank=True, max_length = 40)

my_jquery/models.py
from django.db import models

# Create your models here.

story8/models.py
from django.db import models

# Create your models here.

story9/models.py
from django.db import models

aktivitas/forms.py
from django import forms
from .models import Activity, Person

class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ('name', 'description',)

class PersonForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ('name', 'activity',)

home/forms.py
from django import forms
from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        widgets = {
        'name': forms.TextInput(attrs={'size': 40}), 
        'lecturer': forms.TextInput(attrs={'size': 40}), 
        'credit': forms.TextInput(attrs={'size': 40}),
        'description': forms.TextInput(attrs={'size': 40}),
        }
        fields = ('name', 'credit', 'lecturer', 'description')

story9/forms.py
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    first_name = forms.CharField()
    last_name= forms.CharField()
    
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name')

aktivitas/views.py
from django.shortcuts import render, redirect
from .forms import ActivityForm, PersonForm
from .models import Activity, Person

def Aktivitas(request):
    kegiatans = Activity.objects.all()
    participants = Person.objects.all()
    listObject = []
    for kegiatan in kegiatans:
        kegiatan_partic = []
        for participant in participants:
            if (str(participant.activity) == str(kegiatan)):
                kegiatan_partic.append(participant)
        listObject.append((kegiatan,kegiatan_partic))    
    context = {
        "listObject" : listObject
    }
    return render(request, 'aktivitas/aktivitas.html', context )

def addObject(request):
    id_kegiatan = request.POST.get('id_kegiatan', None)
    name_participant = request.POST.get('name_participant',None)
    nama_kegiatan = request.POST.get('nama_kegiatan', None)
    deskripsi_kegiatan = request.POST.get('deskripsi_kegiatan', None)

    if (deskripsi_kegiatan) :
        Activity.objects.create(name=nama_kegiatan, description=deskripsi_kegiatan)
        # Person.objects.create(name=name_participant, activity=Activity.objects.get(id = id_kegiatan))
    else:
        Person.objects.create(name=name_participant, activity=Activity.objects.get(id = id_kegiatan))
        # Activity.objects.create(name=nama_kegiatan, description=deskripsi_kegiatan)


    return redirect('/activity')

home/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from .forms import MatkulForm
from .models import Matkul

def index(request):
    return render(request, 'home/index.html')
    
def likes(request):
    return render(request, 'home/likes.html')

def firstHTML(request):
    return render(request, 'home/1st-html.html')

def matkul(request):
    Matkuls = Matkul.objects.all()
    
    if request.method == 'POST':
        form = MatkulForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'home/matkul.html', {'form': form, 'matkuls': Matkuls})
    
    form = MatkulForm()
    return render(request, 'home/matkul.html', {'form': form, 'matkuls': Matkuls})

def matkulDetail(request,id):
    matkul = Matkul.objects.get(id=id)
    Matkuls = Matkul.objects.all()
    return render(request,'home/matkul-detail.html',{'matkul':matkul, 'matkuls': Matkuls})

def deleteMatkul(request,id):
    matkul = Matkul.objects.get(id=id)
    if request.method == 'POST' :
        matkul.delete()
        return redirect('/matkul')
    return render(request, 'home/matkul-delete.html',{'matkul':matkul})

my_jquery/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404

def Accordion(request):
    return render(request, 'my_jquery/accordion.html')

story8/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
import requests

def Search(request):
    return render(request, 'story8/search.html')

def SearchInput(request):
    if(request.is_ajax()):
        response = requests.get('https://www.googleapis.com/books/v1/volumes?q=' + request.GET['item'])
        data = response.json()
        return JsonResponse(data)

story9/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm


def Story9(request):
    return render(request, "story9/story9.html")


def Register(request):
    if request.method == "POST":
        form = RegisterForm(request.POST);
        if form.is_valid():
            form.save();
            return redirect('/djangologin/')
    else:
        form = RegisterForm();
    return render(request, "story9/register.html", {'form':form})

aktivitas/templates/aktivitas/aktivitas.html
{% extends 'home/base-solidnavbar.html' %}
{% load static %}
{% block head-footer %}
{% load crispy_forms_tags %}

<body style="padding-top: 64px;">
  <div class="activity-content">
    <h1 style="font-family: 'KoPubBatang-Regular', sans-serif;">Hello and welcome!</h1>
    <hr>
    <button data-toggle="modal" data-target="#tambahKegiatan" >Add Activity</button>
    <br><br>
    {% for i in listObject %}
    
      <div class="col-12 d-flex justify-content-center">
        <div class="card">
          <div class="top">
            <h2>{{ i.0.name }}</h2>
            <h4><i>"{{ i.0.description }}"</i></h4>
          </div>
          <div class="bot">
            <h4><b>Participant:</b></h4>
            {% for j in i.1 %}
              <h5>- {{ j.name }}<h5>
            {% endfor %}
            <button data-toggle="modal" data-target="#tambahParticipant{{ i.0.id }}" style="background: #FFD100;">Sign Up</button>
          </div>
        </div>
      </div>
      <br>
      <div class="modal fade" id="tambahParticipant{{i.0.id}}" tabindex="-1" aria-labelledby="tambahParticipantTitle" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Sign up for {{ i.0.name }}?</h5>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <form action="{% url 'aktivitas:addObject' %}" method="post">
                <div class="modal-body">
                  {% csrf_token %}
                  <input name="id_kegiatan" type="hidden" value="{{ i.0.id }}">
                  <label for="name_participant">Name: </label>
                  <input id="name_participant" name="name_participant" type="text" autofocus>
                </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" class="btn btn-primary">Sign up</button>
          </div>
            </form>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
            
  <div class="modal fade" id="tambahKegiatan" tabindex="-1" aria-labelledby="tambahKegiatanTitle" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Daftar Ikut Acara {{ hasil.0.NamaKegiatan }} ?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'aktivitas:addObject' %}" method="post">
          <div class="modal-body">
            {% csrf_token %}
            <div class="form-group">
              <label for="nama_kegiatan">Activity Name: </label>
              <input id="nama_kegiatan" name="nama_kegiatan" type="text" autofocus>
            </div>
            <div class="form-group">
              <label for="deskripsi_kegiatan">Activity Description: </label>
              <input id="deskripsi_kegiatan" name="deskripsi_kegiatan" type="text" autofocus>
            </div>
          </div>
          <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-primary">Add</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</body>
{% endblock %}

home/templates/home/1st-html.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{% static 'home/css/html1.css' %}" />
    <title>Hello</title>
  </head>
  <body>
    <a href="/">
        <button style="font-size: 40px">go back</button>
    </a>
    <h1>Haloo perkenalkan!!</h1>
    <p></p>
    <img
      src="{% static 'home/images/profilepicture.jpg' %}"
      width="430"
      height="600"
      class="center"
    />
    <p></p>
    <h2>Nama: Naufal Sani</h2>
    <h2>NPM: 1906398723</h2>
    <h2>Angkatan: 2020</h2>
    <h2>Tempat Kuliah: Fasilkom UI</h2>
    <h2>Hobi: Mendengarkan musik</h2>
    <h3>
      Haloo!! Kebiasaan yang sering kulakukan adalah meunda pekerjaan T_T Jangan
      diikutin yaw.
    </h3>
  </body>
</html>

home/templates/home/base-solidnavbar.html
{% load static %}

<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Naufal Sani</title>
    <link rel="shortcut icon" href="{% static 'home/images/favicon.png' %}" />
    <script src="https://code.jquery.com/jquery-2.1.3.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'home/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/fonts.css' %}" />
    {% block custom-css %}<! If there is some update, just add this block to the html>{% endblock %}
  </head>
  
    
      <nav class="navbar navbar-expand-md navbar-light fixed-top navbar-custom" style="background: #FFD100;">
        <a class="navbar-brand" href="/"><img style="width: 35px; height: 35px;" src="{% static 'home/images/favicon.png' %}"></a>
        <a class="navbar-brand" href="/"><span style="color: #ffffff;">Naufal Sani's Web</span></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target" style="background: #ffffff;">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapse_target">
          <ul class="navbar-nav ml-auto">
            <li style="text-align: center">
              <a class="nav-link" style="color: white;" href="/#intro">Home</a>
            <li style="text-align: center">
              <a class="nav-link" style="color: white;" href="/#about">About</a>
            <li style="text-align: center">
              <a class="nav-link" style="color: white;" href="/#my-adventure">My Adventure</a>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
                Story
              </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="text-align:center;">
                  <a class="dropdown-item" href="/matkul">Course</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/activity">Activity</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/accordion">Accordion</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/search">AJAX</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/djangologin">Login</a>
                </div>
            </li>
            <li style="text-align: center">
              <a class="nav-link" style="color: white;" href="/#contact">Contact</a>
          </ul>
        </div>
      </nav>
      
{% block head-footer %}

{% endblock %}

    <section id="contact">
      <div class="row">
        <div class="col-6">
          <br><br>
          <h1 style="text-align:right">Contact</h1>
        </div>
        <div class="col-6">
          <br><br>
          <a href="https://www.instagram.com/afalsani/">
            <img style="width: 50px; height: 50px;" src="{% static 'home/images/instagram.webp' %}" alt="Instagram">
          </a>
          <a href="https://www.linkedin.com/in/naufal-sani-19271a192/">
            <img style="width: 50px; height: 50px;" src="{% static 'home/images/linkedin.webp' %}" alt="Linkedin">
          </a>
          <p>Email: naufalsani2001@gmail.com</p>
        </div>
      </div>
    </section>
</html>

home/templates/home/base.html
{% load static %}

<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Naufal Sani</title>
    <link rel="shortcut icon" href="{% static 'home/images/favicon.png' %}" />
    <script src="https://code.jquery.com/jquery-2.1.3.min.js" integrity="sha256-ivk71nXhz9nsyFDoYoGf2sbjrR9ddh+XDkCcfZxjvcM=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'home/css/main.css' %}">
    <link rel="stylesheet" href="{% static 'home/css/fonts.css' %}" />
    {% block custom-css %}<! If there is some update, just add this block to the html>{% endblock %}
  </head>
  
  <body>
    
    <div class="{% block bg-intro %}bg-intro{% endblock %}" >
      <nav class="navbar navbar-expand-md navbar-light sticky-top navbar-custom">
        <a class="navbar-brand" href="/"><img style="width: 35px; height: 35px;" src="{% static 'home/images/favicon.png' %}"></a>
        <a class="navbar-brand" href="/"><span style="color: #ffffff;">Naufal Sani's Web</span></a>
        <button class="navbar-toggler" data-toggle="collapse" data-target="#collapse_target" style="background: #ffffff;">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapse_target">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" style="color: white;" href="/#intro">Home</a></li>
            <li class="nav-item">
              <a class="nav-link" style="color: white;" href="/#about">About</a></li>
            <li class="nav-item">
              <a class="nav-link" style="color: white;" href="/#my-adventure">My Adventure</a></li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color:white">
                Story
              </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="text-align:center;">
                  <a class="dropdown-item" href="/matkul">Course</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/activity">Activity</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/accordion">Accordion</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/search">AJAX</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/djangologin">Login</a>
                </div>
            </li>
            <li class="nav-item">
              <a class="nav-link" style="color: white;" href="/#contact">Contact</a></li>
          </ul>
        </div>
      </nav>
      
{% block head-footer %}

{% endblock %}

    <section id="contact">
      <div class="row">
        <div class="col-6">
          <br><br>
          <h1 style="text-align:right">Contact</h1>
        </div>
        <div class="col-6">
          <br><br>
          <a href="https://www.instagram.com/afalsani/">
            <img style="width: 50px; height: 50px;" src="{% static 'home/images/instagram.webp' %}" alt="Instagram">
          </a>
          <a href="https://www.linkedin.com/in/naufal-sani-19271a192/">
            <img style="width: 50px; height: 50px;" src="{% static 'home/images/linkedin.webp' %}" alt="Linkedin">
          </a>
          <p>Email: naufalsani2001@gmail.com</p>
        </div>
      </div>
    </section>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block head-footer %}
  
  
    <section id="intro">
        <div class="intro-text">
          <h2>Hello and welcome to my website!</h2>
          <h1>Naufal Sani</h1>
          <h3>A computer Science Student</h3>
        </div>
      </div>
    </section>
    
    <section id="about">
      <br><br>
      <h1>About</h1>
      <hr>
      <div class="row" style="margin-top: 30px">
        <div class="col-12 d-flex justify-content-center">
          <div class="introduction">
            <img src="{% static 'home/images/pp.jpg' %}" alt="Profile Picture">
            <h2 class="lead">Naufal Sani</h2>
            <p class="lead">A Computer Science Student. A learner, a listener. I love riddle question and will try my best to solve it. My favorite movie is 3 Idiots, just because it is funny in someway.</p>
          </div>
        </div>
      </div>
      <div class="row" style="margin-top: 30px">
        <div class="col-12 d-flex justify-content-center">
          <div class="likes">
            <a href="likes">
              <button>Click me!</button>
            </a>
            <h2 class="lead">Get to know me!</h2>
            <p class="lead">Click the button to see things that i like.</p>
          </div>
        </div>
      </div>
      <br><br>
      <div class="row">
        <div class="col-12 d-flex justify-content-center">
            <a href="1st-html">
                <button>Check out my 1st HTML!</button>
            </a>
        </div>
      </div>
      <br><br>
    </section>
    
    <section id="my-adventure">
      <br><br>
      <h1>My Adventure</h1>
      <hr>
      <p style="text-align: center; font-size:20px;"><i>"Here are my adventure, my journey. My past, i enjoyed and i'll remember"</i></p>
      
      <h2>My Education</h2>
        <div class="row">
          <div class="col-md-4">
            <a href="https://www.instagram.com/smpmuhammadiyahcileungsi/">
              <img class="circle-img" href="https://www.cs.ui.ac.id/" src="{% static 'home/images/smpm1c.png' %}" alt="SMP">
            </a>
            <hr>
            <h3>SMP Muhammadiyah 1 Cileungsi</h3>
            <h4>2013-2016</h4>
          </div>
          <div class="col-md-4">
            <a href="https://sman1cileungsi.sch.id/">
              <img class="circle-img" src="{% static 'home/images/nepalc.png' %}" alt="SMA">
            </a>
            <hr>
            <h3>SMA Negeri 1 Cileungsi<h3>
            <h4>2016-2019</h4>
          </div>
          <div class="col-md-4">
            <a href="https://www.cs.ui.ac.id/">
              <img class="circle-img" src="{% static 'home/images/fasilkomc.png' %}" alt="Universitas">
            </a>
            <hr>
            <h3>Unviersitas Indonesia Jurusan Ilmu Komputer</h3>
            <h4>2019-sekarang</h4>
          </div>
        </div>
        
      <h2>My Experience</h2>
        <div class="row">
          <div class="col-md-4">
            <a href="https://www.instagram.com/pmbfasilkomui/">
              <img class="circle-img" href="https://www.cs.ui.ac.id/" src="{% static 'home/images/pmbc.png' %}" alt="PMB Fasilkom 2020">
            </a>
            <hr>
            <h3>Staf at New Student Orientation Fasilkom UI 2020</h4>
            <h4>Documentation Division</h4>
          </div>
          <div class="col-md-4">
            <a href="https://bem.cs.ui.ac.id/">
              <img class="circle-img" src="{% static 'home/images/bemc.png' %}" alt="BEM Fasilkom">
            </a>
            <hr>
            <h3>Staf at BETIS UI 2020</h3>
            <h4>Academic Division</h4>
          </div>
          <div class="col-md-4">
            <a href="https://www.instagram.com/betisfasilkomui/">
              <img class="circle-img" src="{% static 'home/images/betisc.png' %}" alt="Betis">
            </a>
            <hr>
            <h3>Staf at BEM Fasilkom UI 2020</h3>
            <h4>Academic and Leadership Division</h4>
          </div>
        </div>
      <br><br>
    </section>
    
{% endblock %}

home/templates/home/matkul-delete.html
{% extends 'home/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block bg-intro %} bg-matkul {% endblock %}

{% block head-footer %}

    <section id="matkul">
      <div class="matkul-content">
      <h1>Are you sure to delete <i>{{matkul.name}}</i> course ?</h1>
        <form method="post">
          {% csrf_token %}
          <button type="submit" style="margin-top: 30px; background-color: #F72222;"><b>Yes</b></button>
        </form>
        <a href="/matkul/{{matkul.id}}"><button>Cancel</button></a>
      </div>
    </section>

{% endblock %}

story8/templates/story8/search.html
{% extends 'home/base-solidnavbar.html' %}
{% load static %}
{% block custom-css %}
    <link rel="stylesheet" href="{% static 'story8/story8.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}
{% block head-footer %}

<div class="content" style="padding-top:65px; min-height:100%;">
    <br>
    <input type="text" id="searchBox" name="item" placeholder="Search..."/>
    <button id="searchButton"><i class="fa fa-search"></i></button>
    <section id="searchResult">
    </section>
    <br>
</div>

<script>
    var search_url = "{% url 'story8:searchInput' %}?item=";
    
    var button = document.getElementById("searchButton");
    button.addEventListener("click", function() {
        var pencarian = $("#searchBox").val();
        cariBuku(pencarian);
    });
    
    var input = document.getElementById("searchBox");
    input.addEventListener("keyup", function(event) {
      // Number 13 is the "Enter" key on the keyboard
      if (event.keyCode === 13) {
        var pencarian = $("#searchBox").val();
        cariBuku(pencarian);
      }
    });

    cariBuku = (search_value) => {
        $.ajax({
            type:"GET",
            url: search_url + search_value,
            dataType: "json",
            success: function(data) {
                $('#searchResult').empty();
                for (i of data.items) {
                    var info = i.volumeInfo
                    console.log(info.title);
                    
                    var title = info.title ? info.title : "";
                    
                    var author = info.authors;
                    if (author == undefined ) {
                        author = "<i>Unknown</i>"
                    } else {
                        author = info.authors[0];
                    }
                    
                    var deskripsi = info.description ? info.description: "-";
                    
                    var img = info.imageLinks.smallThumbnail;
                    if (!img) {
                        img = info.imageLinks.smallThumbnail;
                    } else if (!img) {
                        img = "https://www.freeiconspng.com/uploads/no-image-icon-8.png";
                    }
                    
                    var linkBaca = info.previewLink ? info.previewLink: "";
                    
                    var tanggal = info.publishedDate  ? info.publishedDate: "<i>Unknown</i>";
                    
                    /*var result = '\
                    <div class="d-flex bookCard" style="padding: 15px; background-color: #3E4D5E; border-radius:20px">\
                   <img src=' +img + 'height="195px" width="128px" style="margin: 0 30px 0 0">\
                   <div style="color: white;">\
                      <h3 >'+title+'</h3>\
                      <h6>' + tanggal+ '</h6>\
                      <h6>Author : '+author+'</h6>\
                      <p>' + deskripsi + '</p>\
                      <a type="button" class="btn btn-primary" href= '+ linkBaca +'>Read</a>\
                   </div>\
                </div>'
                    $("#searchResult").append(result);*/
                
                    var result = '\
                    <div class="row" style="margin-top: 30px">\
                        <div class="col-12 d-flex justify-content-center">\
                          <div class="book">\
                            <div class="right">\
                                <a href = "'+ linkBaca +'"> <img src="' + img + '">\
                            </div>\
                            <div class="lead">\
                                <h2>' + title + '</h2></a>\
                                <p style="text-align:center"><i>Author</i>: ' + author + '</p>\
                                <p>'+ deskripsi +'</p>\
                                <p style="text-align:right"><i>Release Date</i>: <u>' + tanggal + '</u></p>\
                            </div>\
                          </div>\
                        </div>\
                      </div>'
                    $("#searchResult").append(result);
                }
            }
        })
    }
</script>

{% endblock %}